# Generated by Django 5.0 on 2025-07-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('home', 'Home'), ('toys', 'Toys'), ('car', 'car'), ('bicycle', 'bicycle'), ('clothe', 'clothe'), ('shoe', 'shoe'), ('bag', 'bag'), ('gun', 'gun'), ('caps', 'cap'), ('house', 'house')], default='other', max_length=50),
        ),
    ]
