# Generated by Django 5.0 on 2025-07-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('home', 'Home'), ('toys', 'Toys'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('clothe', 'Clothe'), ('shoe', 'Shoe'), ('bag', 'Bag'), ('gun', 'Gun'), ('cap', 'Cap'), ('house', 'House')], default='other', max_length=50),
        ),
    ]
