# Generated by Django 5.0 on 2025-07-08 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('membership', models.CharField(choices=[('Platinum Fan', 'Platinum Fan'), ('Gold Fan', 'Gold Fan'), ('Silver Fan', 'Silver Fan'), ('Bronze Fan', 'Bronze Fan')], max_length=50)),
                ('valid_till', models.DateField()),
                ('issued_on', models.DateField(auto_now_add=True)),
                ('fan_photo', models.ImageField(upload_to='fan_cards/photos/')),
                ('keanu_photo', models.ImageField(default='default_keanu.jpg', upload_to='fan_cards/keanu/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
