# Generated by Django 5.0 on 2025-07-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fancard',
            name='membership',
            field=models.CharField(choices=[('Platinum Fan', 'Platinum Fan'), ('Gold Fan', 'Gold Fan'), ('Silver Fan', 'Silver Fan'), ('Bronze Fan', 'Bronze Fan'), ('Vip Fan', 'Vip Fan')], max_length=50),
        ),
    ]
