# Generated by Django 5.0 on 2025-07-11 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Express', 'Express'), ('Standard', 'Standard'), ('Economy', 'Economy'), ('Customs clearance (Bounded)', 'Customs clearance (Bounded)'), ('China to UAE as FCL and LCL', 'China to UAE as FCL and LCL'), ('Courier air Shipping to Lebanon', 'Courier air Shipping to Lebanon'), ('Transportation Service To All Over The World', 'Transportation Service To All Over The World'), ('Warehousing. Storage and handling services.', 'Warehousing. Storage and handling services.'), ('FCL & LCL Shipping by sea all over the world.', 'FCL & LCL Shipping by sea all over the world.'), ('Door to DOOR FTL land shipping to GCC Country', 'Door to DOOR FTL land shipping to GCC Country')], max_length=100)),
                ('commodity', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Documents', 'Documents'), ('Energy Commodities', 'Energy Commodities'), ('Metals Commodities', 'Metals Commodities'), ('Agricultural Commodities', 'Agricultural Commodities'), ('Livestock and Meat Commodities', 'Livestock and Meat Commodities'), ('Grains Commodities', 'Grains Commodities'), ('Precious Metals', 'Precious Metals'), ('Base Metals', 'Base Metals'), ('Industrial and Construction Commodities', 'Industrial and Construction Commodities'), ('Fertilizers', 'Fertilizers'), ('Other', 'Other')], max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('In Transit', 'In Transit'), ('At Customs', 'At Customs'), ('Delivered', 'Delivered')], default='Processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
