# Generated by Django 5.0 on 2025-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='weight',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='commodity',
            field=models.CharField(choices=[('Fertilizers', 'Fertilizers'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('home', 'Home'), ('toys', 'Toys'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('clothe', 'Clothe'), ('shoe', 'Shoe'), ('bag', 'Bag'), ('gun', 'Gun'), ('cap', 'Cap'), ('house', 'House')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('In Transit', 'In Transit'), ('At Customs', 'At Customs'), ('Delivered', 'Delivered')], default='Processing', max_length=20),
        ),
    ]
