# Generated by Django 5.0 on 2025-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_shipment_quantity_remove_shipment_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='commodity',
            field=models.CharField(choices=[('Platinum Fan', 'Platinum Fan'), ('Gold Fan', 'Gold Fan'), ('Silver Fan', 'Silver Fan'), ('Bronze Fan', 'Bronze Fan'), ('Vip Fan', 'Vip Fan'), ('Fertilizers', 'Fertilizers'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('books', 'Books'), ('home', 'Home'), ('toys', 'Toys'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('clothe', 'Clothe'), ('shoe', 'Shoe'), ('bag', 'Bag'), ('gun', 'Gun'), ('cap', 'Cap'), ('house', 'House')], max_length=100),
        ),
    ]
