# Generated by Django 5.0 on 2025-07-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_shipment_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(default='Processing', max_length=100),
        ),
    ]
