# Generated by Django 5.0 on 2025-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_shipment_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(default='Processing', editable=False, max_length=100),
        ),
    ]
